#
#server:
#  port: 8081
#
#spring:
#  boot:
#    admin:
#      url: http://localhost:8080
#      client:
#        url: http://localhost:8080
#        username: admin
#        password: admin
#        instance:
#          metadata:
#            user.name: admin
#            user.password: admin
#          service-url: http://localhost:8081
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always